title = "kewt"
style = "kewt"
dir_indexes = true
single_file_index = true
flatten = false
footer = "<a href=\"https://kewt.krzak.org\"><img src=\"/button.gif\" /></a>"
logo = ""
display_logo = false
display_title = true
logo_as_favicon = false
favicon = "favicon.ico"
order = "Home, docs, depths, heaven"
home_name = "Home"
show_home_in_nav = true
nav_links = ""
nav_extra = ""
generate_page_title = true
error_page = "not_found.html"
versioning = true
enable_header_links = true
base_url = "https://kewt.krzak.org"
custom_admonitions = ""
generate_feed = false
feed_file = "rss.xml"
posts_dir = ""