title = "kewt"
style = "kewt"
dir_indexes = true
single_file_index = true
flatten = false
footer = "<a href="https://kewt.krzak.org"><img src="/button.gif" /></a>"
logo = ""
display_logo = false
display_title = true
logo_as_favicon = true
favicon = ""
order = ""
